import type { Metadata } from 'next';
import { startMSWServer } from '@/mocks/server';
import localFont from 'next/font/local';
import MSWClientProvider from '@/mocks/mswClientProvider';
import './globals.css';

/** 루트 레이아웃 컴포넌트는 서버 컴포넌트이니 서버용 MSW 초기화 코드는 여기 맨위에서 실행하도록 했습니다 */
import('@/mocks/server').then(() => {
  startMSWServer();
});

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(pretendard.variable);
  return (
    <html lang="en">
      <body className={`${pretendard.variable} font-pretendard pretendard`}>
        <MSWClientProvider>{children}</MSWClientProvider>
      </body>
    </html>
  );
}
