name: Deploy Storybook

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        run: yarn build-storybook
        env:
          CI: true

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        run: yarn build-storybook
        env:
          CI: true

      - name: Debug - List built files
        run: |
          echo "=== Storybook static files ==="
          find storybook-static -name "*.svg" | head -10
          echo "=== Directory structure ==="
          ls -la storybook-static/
          echo "=== HTML content check ==="
          grep -n "chevron-down" storybook-static/index.html || echo "chevron-down not found in index.html"
          echo "=== Check if base path is set ==="
          grep -n "DDD-12-GROWIT-FE" storybook-static/index.html || echo "Base path not found in HTML"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
