name: Manual Trigger Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: '배포할 브랜치 선택'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - develop

jobs:
  deploy:
    uses: /.github/workflows/main.yml
    with:
      branch: ${{ github.event.inputs.branch }}
    secrets: inherit